### ISSUE TITLE
Add delay before hide

### ISSUE THREAD

**Issue by MichMich** [istvan-ujjmeszaros/bootstrap-autohidingnavbar#16]
It would be great if you can add an option to set a delay before the bar hides.

**Comment by allanedk** [comment]
Agree. 

It would be a nice option to be able to set a minimum scroll length in pixels before the menu hides.

**Comment by istvan-ujjmeszaros** [comment]
@MichMich what do you think about the pixels? Is that good for you or you would prefer a timer?

**Comment by MichMich** [comment]
I would prefer a timer. But both would work. :)

**Comment by allanedk** [comment]
The reason I suggested pixels instead of a timer is that we use auto hide on a header menu that is set to XX pixels. In addition to this there is a padding-top on the body-tag to ensure that the top menu will not cover any content when loading a page.

In the current version we experience problems on mobile devices, because the menu hides too early. I.e. the menu hides when the user scrolled only XX-20px, breaking the layout as is leaves a "blank space". 

An option to prevent the menu from hiding before the user has scrolled at least XX pixels, would solve this issue.
